# This is a basic workflow to help you get started with Actions
name: Docker Build Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: dmcallejo
      DOCKER_IMAGE_NAME: asfbot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sets env vars for tag latest
        run: |
          echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
        if: startsWith(github.ref_name, 'master')
      - name: Sets env vars for staging
        run: |
          echo "DOCKER_IMAGE_TAG=develop" >> $GITHUB_ENV
        if: startsWith(github.ref_name, 'develop')
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.x64
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      # Now build and push to Dockerhub
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build_DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.x64
          tags: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
